name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml
      - zmk_modules/**
      - .github/workflows/build-nix.yml

jobs:
  build:
    uses: renxida/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr
